variables:
  poolName: 'default'
  reviewAppResource: 'review-env-check'
  content-to-pr: 'Heyo testing'
 
jobs:
- deployment: deploy
  environment: desattir.$(RandomVariable)
  pool: $(poolName)
  strategy:
    runOnce:
      deploy:
        steps:
        - reviewApp: default
        - task: Kubernetes@1
          displayName: 'Create namespace'
          inputs:
            command: create
            arguments: 'ns $(reviewAppResource) --dry-run -o json | kubectl apply -f -'
