variables:
  poolName: 'default'
  reviewAppResource: 'review-env-check'
  content-to-pr: 'Heyo testing'
 
jobs:
- deployment: deploy
  environment: desattir.$(RandomVariable)
  pool: $(poolName)
  strategy:
    runOnce:
      deploy:
        steps:
        - reviewApp: default
        - task: Kubernetes@1
          displayName: 'kubectl create namespace'
          inputs:
            command: apply
            inline: { "kind": "Namespace", "apiVersion": "v1", "metadata": { "name": "$(reviewAppResource)" }}
