variables:
  poolName: 'default'
  reviewAppResource: 'review-env-check'
  content-to-pr: 'Heyo testing'
 
jobs:
- deployment: deploy
  environment: desattir.$(reviewAppResource)
  pool: $(poolName)
  strategy:
    runOnce:
      deploy:
        steps:
        - reviewApp: default
        
        - task: Kubernetes@1
          displayName: 'kubectl get'
          inputs:
            connectionType: 'Kubernetes Service Connection'
            namespace: '$(reviewAppResource)'
            command: get
            arguments: pods
        
        - script: echo ##vso[task.setvariable variable=GITHUB_COMMENT;]Github automated comment
