apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: dsmsapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dsmsapp 
    spec:
      containers:
        - name: dsmsapp 
          image: desattiracr.azurecr.io/dsmsapp
          ports:
          - containerPort: 80