name: Lint

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: azure/k8s-lint@releases/v1
        with:
          lintType: dryrun
          manifests: |
             manifests/deployment.yml
             manifests/service.yml
