name: Lint

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ds-ms/k8s-lint@master
        with:
          manifests: |
             manifests/deployment.yml
             manifests/service.yml
          lintType: dryrun
