name: Lint

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: azure/k8s-lint@v1
        with:
          manifests: |
             manifests/deployment.yml
             manifests/service.yml
